<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.14"/>
    <xacro:property name="chassis_width" value="0.175"/>
    <xacro:property name="chassis_height" value="0.110"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.034"/>
    <xacro:property name="wheel_thickness" value="0.025"/>
    <xacro:property name="wheel_mass" value="0.02"/>
    <xacro:property name="chassis_offset_x" value="0.07"/>
    <xacro:property name="wheel_offset_y" value="0.1"/>
    <xacro:property name="chassis_offset_z" value="0.035"/>
    <xacro:property name="caster_wheel_radius" value="0.03"/>
    <xacro:property name="caster_wheel_mass" value="0.04"/>
    <xacro:property name="caster_wheel_offset_x" value="0.02"/>
    <xacro:property name="caster_wheel_offset_z" value="-0.04"/> 
    <!-- ${wheel_offset_z - wheel_radius + caster_wheel_radius}"/> -->


     <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->
    <link name="base_link">
         <pose>0 0 0 0 0 0</pose>
    </link>

    <!-- BASE_FOOTPRINT LINK -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>        
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>


    <link name="base_footprint">  </link>


    <!-- CHASSIS LINK -->
    <!-- The box origin is at the bottom and back, the chassis relate to base_link is -->
    <!-- chassic move left by ( ${-wheel_offset_x} ) and move up by ${wheel_offset_z}) -->
    <!-- relative to the origin <0, 0, 0>-->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-chassis_offset_x} 0 ${chassis_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->
    <!-- clockwise==(negative rotation) counterclockwise== (positive rotation)-->
    <!-- right hand rule -->
    <!-- axis z is "1", car is moving fordward-->
    <joint name="front_left_wheel_joint" type="continuous">
        <origin xyz="0.05 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" /> 
        <parent link="base_link"/>
        <child link="front_left_wheel"/>        
        <axis xyz="0 0 1"/>
    </joint>

    <link name="front_left_wheel">
        <visual name='front_left_wheel_visual'>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

     <joint name="rear_left_wheel_joint" type="continuous">
        <origin xyz="-0.05 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" /> 
        <parent link="base_link"/>
        <child link="front_left_wheel"/>        
        <axis xyz="0 0 1"/>
    </joint>

    <link name="rear_left_wheel">
        <visual name='rear_left_wheel_visual'>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="front_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="rear_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- RIGHT WHEEL LINK -->
    <joint name="front_right_wheel_joint" type="continuous">
        <origin xyz="0.05 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <parent link="base_link"/>
        <child link="front_right_wheel"/>
        
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="front_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="rear_right_wheel_joint" type="continuous">
        <origin xyz="-0.05 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <parent link="base_link"/>
        <child link="front_right_wheel"/>
        
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="rear_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="front_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="rear_right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

</robot>